# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Next.js app to Azure Web App - devopstrio-global-QA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'BlueHeart-Saga/Devopstrio'
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    env:
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      NEXT_PUBLIC_COMPANY_ID: ${{ secrets.NEXT_PUBLIC_COMPANY_ID }}
      NEXT_PUBLIC_PRODUCTION_DOMAIN: ${{ secrets.NEXT_PUBLIC_PRODUCTION_DOMAIN }}
      NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
      AZURE_CDN_URL: ${{ secrets.AZURE_CDN_URL }}
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      NEXT_PUBLIC_CONTACT_EMAIL: ${{ secrets.NEXT_PUBLIC_CONTACT_EMAIL }}
      NEXT_PUBLIC_SUPPORT_EMAIL: ${{ secrets.NEXT_PUBLIC_SUPPORT_EMAIL }}
      NEXT_PUBLIC_PRIVACY_EMAIL: ${{ secrets.NEXT_PUBLIC_PRIVACY_EMAIL }}
      NEXT_PUBLIC_TRUST_EMAIL: ${{ secrets.NEXT_PUBLIC_TRUST_EMAIL }}
      NEXT_PUBLIC_DPO_EMAIL: ${{ secrets.NEXT_PUBLIC_DPO_EMAIL }}
      NEXT_PUBLIC_LEGAL_EMAIL: ${{ secrets.NEXT_PUBLIC_LEGAL_EMAIL }}
      NEXT_PUBLIC_INTERNSHIP_EMAIL: ${{ secrets.NEXT_PUBLIC_INTERNSHIP_EMAIL }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: npm install and build
        run: |
          npm ci
          npm run build

      - name: Zip artifact for deployment
        run: zip -qq -r release.zip . -x "*.git*"

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'devopstrio-global-QA'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: release.zip